id: P4B0414A1
initial_creation_type: input
source_metadata:
  title: Hagiography of dPal ldan bla ma Ku ma ra ma ti (1372–1475)
  author: gser mdog paN chen shAkya mchog ldan/
  description: 'Digital version 4.0 {Wylie}; WYLIE COPY of master xml (completed:
    2012-09); head entries supplemented and linebreaks encoded, revision in process,
    no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/360
  bases:
    a790:
      title: Hagiography of dPal ldan bla ma Ku ma ra ma ti (1372–1475)
      order: 1
      base_file: a790.txt
created_at: '2022-04-15T18:59:23.769091'
last_modified_at: '2022-04-15T18:59:23.769099'
quality: null
